### ISSUE TITLE
The Mad Bomber is always auto firing

### ISSUE THREAD

**Issue by angstsmurf** [dcsch/yazmin#11]
[The Mad Bomber](https://ifdb.tads.org/viewgame?id=kbcjvrtghsw57ldp) seems to be always bombing whether the player presses space or not, which makes it unplayable. It works correctly in Gargoyle.

**Comment by dcsch** [comment]
Fixed with the changes in handling input with 80d95c3623fa6b8f91bee93bca6d9fc20cad7ffb.
