### ISSUE TITLE
Problems with non ASCII characters - Dialog

### ISSUE THREAD

**Issue by mikawa** [dcsch/yazmin#13]
I've encoutered a problem with non ASCII characters in input line, but only when a story file is compiled with Dialog Compiler from Linus Akesson to z-code.
The terp does not recognize the input line so the z-machine does not understand the command. This affects (for now) German, but I think it will also affect other translations, e.g. someone is working on a japanese translation now.

I would be glad if you can fix this, as there is mometarily no other "native" interpreter on OSX (I am using Catalina).
However, Lectrote is working without problems.

**Comment by dcsch** [comment]
@mikawa Would it be possible to include a small snippet of Dialog code that reproduces this problem?

**Comment by mikawa** [comment]
@dcsch Yes, of course.
Just 

```
(current player #player)
(#player is #in #room)

#room
(room *)

(understand [öffne | $Words] as [open $Obj])
	*(understand $Words as non-all object $Obj)

#chest
(item *)
(name *)    chest
(container *)
(* is handled)
(* is #in #room)
```

then try typing "öffne chest" (which works correctly on osx-gargoyle or osx-lectrote
