### ISSUE TITLE
Problem printing out em dash

### ISSUE THREAD

**Issue by lkcampbell** [dcsch/yazmin#15]
## Repro steps:
1. Launch [You've Got a Stew Going!](https://ifdb.tads.org/viewgame?id=dqqpdmlkuw8o9e05)
1. Type in `x drew`

## Observed behavior:
`Drew is one of those rats who you don't necessarily have to constantly suspect of treacheryâthough of course it never hurts. His brown fur is unkempt and his left ear has a big chunk missing.`

Looks like the interpreter is having problems printing out the em dash between "treachery" and "though".

## Expected behavior:
`Drew is one of those rats who you don’t  necessarily have to constantly suspect of  treachery—though of course it never hurts. His  brown fur is unkempt and his left ear has a big  chunk missing.`

**Comment by dcsch** [comment]
Looks like this bug was introduced with the revised UTF-8 handling in the last release, as beta 4 handles it correctly. Time for more unit tests. Thank you @lkcampbell!
