### ISSUE TITLE
Quote text box blocks game text

### ISSUE THREAD

**Issue by lkcampbell** [dcsch/yazmin#16]
## Repro steps:
1. Launch [Curses!](https://ifdb.tads.org/viewgame?id=plvzam05bmz3enh8)
1. Type in `i`
1. Scroll the text up and down, and observe pop up quote text box
1. Type in `z`
1. Observe what happens to the pop up quote text box

## Observed behavior:
After typing in `i` the quote text box covers up the previous game text.

After typing in `z` the quote text box stays on the screen.

## Expected behavior:
I looked at Gargoyle and Lectrote as a comparison.

After typing in `i` the quote text box opens in a frame between the status bar and the game text. The game text still scrolls without affecting the position of the quote text box.

After typing in `z` the quote text box disappears.

**Comment by dcsch** [comment]
This is actually a feature! The box quote is being handled in a fashion similar to Zoom—the quote is being imprinted in the lower window rather than holding the upper window open for one turn.

Saying that, I'll make a change that brings it closer in line with Zoom. I'll cause the box quote to become semi-transparent on the next turn.

**Comment by dcsch** [comment]
cd1bbf1f94e1804789093167abd97ddf0ad5e83c causes the box quote to disappear (or not). Depending on the fade setting, the box quote will either disappear on the next turn (the default), fade out over the specified number of turns, or stay visible always.

Now, a Preferences control needs to be added.

**Comment by lkcampbell** [comment]
Yes, that was just what I was going to suggest. Make it a preference.

**Comment by lkcampbell** [comment]
FYI, I installed Zoom so I can look at its behavior as well when comparing interpreters.

**Comment by angstsmurf** [comment]
The behaviour of quote boxes in Zoom is meant to imitate the look of quote boxes in the original Infocom interpreters, where they were just printed permanently on top of the game text and then scrolled off screen along with it. See for example Trinity on DOS here:
https://youtu.be/0R6PIGzUKeM?t=299

**Comment by lkcampbell** [comment]
@angstsmurf, thanks for the info. From a historical standpoint that certainly makes sense.
