### ISSUE TITLE
URL to IFDB needs updating

### ISSUE THREAD

**Issue by angstsmurf** [dcsch/yazmin#29]
It seems that the Fetch Metadata function no longer downloads cover images since the IFDB server move. Updating [the URL on line 40 in IFStory.m](https://github.com/dcsch/yazmin/blob/master/Yazmin/IFStory.m#L40) to `http://ifdb.org/api/xmlns` seems to fix this.

**Comment by dcsch** [comment]
Ah! OK, it looks like I missed the IFDB announcement. Thank you, I'll get an update done posthaste.

**Comment by angstsmurf** [comment]
It might actually be due to a bug or oversight on behalf of the IFDB people, as I remember reading in the announcement that old links were supposed to be redirected and working, though I can't find the exact wording now. Perhaps this should be reported at the [IFDB suggestion tracker](https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues).

**Comment by dcsch** [comment]
The links are redirecting, but that change is a change in the namespace, so our iFiction parser is going to ignore elements belonging to a namespace it doesn't know about.

**Comment by dcsch** [comment]
Fixed in f24cb26a21ac983d3b5c49774b37458b75f801fe
