### ISSUE TITLE
1.0 Release on Github?

### ISSUE THREAD

**Issue by bryanrieger** [dcsch/yazmin#30]
Any chance of having official releases available via GitHub?

Whenever possible I try to avoid downloading apps from the app store and my Xcode/ObjC knowledge to build from the source is limited.

**Comment by dcsch** [comment]
I'll be preparing a release shortly.

**Comment by dcsch** [comment]
v1.0.1 is now on the releases page: https://github.com/dcsch/yazmin/releases/tag/v1.0.1
