### ISSUE TITLE
Save freezes app

### ISSUE THREAD

**Issue by lkcampbell** [dcsch/yazmin#32]
## Repro steps:
1. Launch any game.
1. Type `save`

## Observed behavior:
App freezes. Have to force quit.

## Expected behavior:
Saves game.

**Comment by dcsch** [comment]
Ouch. It looks like the sandbox permissions are not allowing this to function.

**Comment by cfurlin** [comment]
Just go into xcode and set user file access from read to read-write.

**Comment by dcsch** [comment]
Yes, that fixes it. Time for a new release.
