### ISSUE TITLE
Update code for Apple Silicon M1

### ISSUE THREAD

**Issue by Alvarez81** [dcsch/yazmin#33]
Hi, could be the code compiled as universal app ?

...for arm (M1) compatibility

**Comment by Alessandro1970** [comment]
Yazmin is a very good Z-Machine Interpreter for Mac and now all mac have the Apple Silicon CPU, Rosetta 2 is not a good way and textual **Adventures** should not be forgotten.

**Comment by dcsch** [comment]
Yazmin has been build as a Universal App since release, and as far as I know has supported Apple Silicon since release. I've just double-checked Activity Monitor on an M2 MacBook Pro and it is running as "Apple".
