### ISSUE TITLE
Unable to reposition window

### ISSUE THREAD

**Issue by pheriwinkle** [dcsch/yazmin#35]
After loading the app, I cannot reposition the Window.  (By dragging the titlebar of the main window.)  I can change its size in any direction, which is  a workaround.  (Took me a while to figure that out.)

This is the case on both an M1 machine and an Intel machine.  Both running Sonoma 14.2.1.

**Comment by patneill** [comment]
Can confirm this issue on an M1 machine.

**Comment by dcsch** [comment]
This should be fixed with 7964e88c6909dd7bf83d0a7f49ec8e42d040a63a. App Store will be updated shortly.
