### ISSUE TITLE
IF Library window doesn't indicate when a file has been deleted

### ISSUE THREAD

**Issue by lkcampbell** [dcsch/yazmin#9]
## Repro steps:
1. Launch any Z-machine work that is not already listed in the IF Library window, then close the work down.
1. Delete the Z-machine file.
1. Right click on the IF Library entry for the work and select Open.
1. Right click on the IF Library entry for the work and select Get Info.

## Observed behavior:
After both steps 3 and 4 have been performed, nothing happens. There is no feedback that the file has been deleted.

## Expected behavior:
After both steps 3 and 4 have been performed, some sort of information should be provided to the user that the underlying file has been deleted and maybe an option to remove the entry.

Another idea, automatically remove the IF Library entry from the list if the file it points to no longer exists. This might be less desirable since the user might get confused as to why the entry suddenly disappears.

**Comment by dcsch** [comment]
I'll have an alert sheet appear, with the option included to remove the entry.
